name: Build

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*.*.*"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-15, ubuntu-22.04]
        addrsize: ["64"]
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Homebrew Packages
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: brew install ninja
      - name: Install Linux depencencies
        if: runner.os == 'linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y \
            ninja-build libasound2-dev \
            libpulse-dev libpipewire-0.3-dev \
            libjack-dev libdbus-1-dev

      - uses: secondlife/action-autobuild@v5
        with:
          addrsize: "64"
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: true
